version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    command: ["npm", "start"]
